export enum ErrorCode
{
    ERR_DUPLICATE_LABEL = 100,
    ERR_DUPLICATE_SCREEN = 101,
    ERR_DUPLICATE_IMAGE = 102,
    ERR_DUPLICATE_TRANSFORM = 103,

    ERR_COLON_EXPECTED = 115,
    ERR_IDENTIFIER_EXPECTED = 116,
    ERR_NON_EMPTY_BLOCK_EXPECTED = 117,

    ERR_LABEL_NOT_DEFINED = 518,
    ERR_SCREEN_NOT_DEFINED = 519,
    WRN_IMAGE_NOT_DEFINED = 520,
    ERR_TRANSFORM_NOT_DEFINED = 521
}
